pub mod pump_fun;   // generated by build.rs
pub mod cli;
pub mod config;
pub mod crypto;
pub mod wallet;
pub mod oracle;
pub mod scanner;
pub mod pool;
pub mod strategy;
pub mod transaction;
pub mod trade;
pub mod runner;
pub mod logging;
pub mod models;
pub mod error;
